### ISSUE TITLE
Every priority change on items should end up on a new line.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Bsexy-Shop#111]
Client wants to have new set of priority to appear on new line. We should find a way to break after _last_ of certain priority class.

**Comment by talrez11** [comment]
Are there any suggestions on how to achieve that?
Because how can i be sure, or how do i target the eight item of a specific priority range and still leave room to fill eight of the same kind

**Comment by MeanEYE** [comment]
~~It can be done with CSS.~~ Has to be done with JS.

**Comment by talrez11** [comment]
Pushed and ready for deployment
