### ISSUE TITLE
Create menu in item view which shows all the categories item belongs to.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Bsexy-Shop#112]
When displaying individual shop items we need to include a list of all the categories item belongs to. This needs to be done by calling:

```xml
<cms:module
    name="shop"
    action="show_cateogory_list"
    item="$params['id']"
    cms:eval="item"
    />
```
Talk to designer regarding styling.

Page templates to modify:

- Item view;
- Search result;
- Promoted item view.

**Comment by talrez11** [comment]
Can be deployed
