### ISSUE TITLE
Create simple city subcategories menu on service page.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Bsexy-Shop#13]
Below service title we need to have a list of links leading to each city sub category.

![screenshot from 2016-10-13 14-19-00](https://cloud.githubusercontent.com/assets/1911594/19348851/4241c59c-9150-11e6-884f-cb3ee6f453ab.png)

**Comment by talrez11** [comment]
Subcategory links are added but i would like to show only city names without category name.Help needed
