### ISSUE TITLE
Reduce font size and remove boldness from categories on item page

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Bsexy-Shop#146]
Reduce font size and remove boldness from categories on item page

**Comment by MeanEYE** [comment]
![screenshot from 2017-03-28 11-25-35](https://cloud.githubusercontent.com/assets/1911594/24395736/4ac63b7c-13a9-11e7-9325-7510b6f5307c.png)
He's referring to this part.

**Comment by iliyaM** [comment]
fixed needs to be checked on live site.
