### ISSUE TITLE
The expiration date is not set when creating a new item

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Bsexy-Shop#149]
![image](https://cloud.githubusercontent.com/assets/18681483/24701272/7cbc2c86-1a02-11e7-8833-8bac6d73641c.png)

**Comment by MeanEYE** [comment]
![image](https://cloud.githubusercontent.com/assets/1911594/24702670/80f5f5e2-1a08-11e7-98c2-caabe554150b.png)
Tested. Seems to work properly. They need to clear cache or something.

**Comment by hanan-avzuk** [comment]
Its on my PC and the cache has been cleared and still I get it without set date

**Comment by MeanEYE** [comment]
@iliyaM double-check, you are Chrome user.

**Comment by iliyaM** [comment]
Not working (shop item & bsexy shop item)

![screenshot from 2017-04-05 14-22-24](https://cloud.githubusercontent.com/assets/20294485/24703332/7e0ea06a-1a0b-11e7-820b-f5d98cc5844f.png)

**Comment by MeanEYE** [comment]
Fixed.
