### ISSUE TITLE
Show search field in Google search results.

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Bsexy-Shop#155]
Search field should appear at google results like here : 

(https://www.google.co.il/search?q=%D7%A1%D7%A7%D7%A1+%D7%90%D7%93%D7%99%D7%A8&rlz=1C1CHBF_enIL738IL738&oq=%D7%A1%D7%A7%D7%A1+%D7%90%D7%93%D7%99%D7%A8&aqs=chrome..69i57j69i61.4183j0j4&sourceid=chrome&ie=UTF-8
)

**Comment by MeanEYE** [comment]
This seems to be Google's willpower to show it or not.  I will check in details with their requirements ([here](https://webmasters.googleblog.com/2014/09/improved-sitelinks-search-box.html) and [here](http://schema.org/docs/actions.html?utm_source=wmc-blog&utm_medium=direct-referral&utm_campaign=sitelinks-searchbox)). On first glance we are doing everything right but I want to double check before rejecting this issue.

**Comment by MeanEYE** [comment]
Do additional research.
