### ISSUE TITLE
Reposition list of categories on item details page.

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Bsexy-Shop#158]
At the item page there are list of categories that items belong to. That list should be lowered to be in the same line as the small thumbnails of the product.

**Comment by iliyaM** [comment]
![screenshot from 2017-05-04 10-30-32](https://cloud.githubusercontent.com/assets/20294485/25694008/024d14d2-30b5-11e7-9274-64c46b02755e.png)


This is what you meant?

**Comment by MeanEYE** [comment]
Yes!
