### ISSUE TITLE
Date

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Bsexy-Shop#160]
The expiration date does not update automatically.

**Comment by MeanEYE** [comment]
Can @talovdat or @hanan-avzuk test both test and public? I want to make sure this is indeed an issue that needs fixing instead of just caching problem.

**Comment by hanan-avzuk** [comment]
https://drive.google.com/file/d/0B0JS03dvjjuOZG9xRm11ZUFDWW8/view

**Comment by MeanEYE** [comment]
@hanan-avzuk please check test for this site.

**Comment by hanan-avzuk** [comment]
Both test and regular site do not work properly, I've doubled check that...

**Comment by MeanEYE** [comment]
This is fixed, just for some reason wrong JS file is cached.
