### ISSUE TITLE
Ability to copy phone number from backend.

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Bsexy-Shop#161]
Phone number at manege item should be regular text so they can copy it.

**Comment by MeanEYE** [comment]
Are you referring to backend?

**Comment by talovdat** [comment]
Yes.

**Comment by MeanEYE** [comment]
Why would they need to copy phone number? I don't understand this workflow.

**Comment by talovdat** [comment]
"In order to tatto it on thier asses, why do you care?". quating Hanan.
