### ISSUE TITLE
Change the order of mobile menu items.

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Bsexy-Shop#164]
Change the order of the categories as it should be by the order of the categories along the page.

Meaning: at the top of the home page you can see the icons of the categories, just put them in the order (from right to left) as the categories along the page goes in .

**Comment by talovdat** [comment]
Beware - Mobile version.

**Comment by MeanEYE** [comment]
This makes zero sense what you just said. And please stop with the stupid stars dashes and other shit.

**Comment by MeanEYE** [comment]
Translation: _Change the order of mobile menu items to be the same as home page categories._

**Comment by MeanEYE** [comment]
To which I say, we shouldn't do this as currently client is the one ordering items by the "Order" thing they asked for specifically. In my opinion order of home page categories is the one that should change.

**Comment by MeanEYE** [comment]
Okay, so it seems that we need to do this after all. Mobile version of the menu should be ordered the same way as categories on mobile home page. Desktop version should be kept as is and separated with `cms:desktop` / `cms:mobile` tags.
