### ISSUE TITLE
Make sure banner sizes are up to spec in CSS.

### ISSUE THREAD

**Issue by MeanEYE** [Way2CU/Bsexy-Shop#169]
At some point banners were split in half horizontally leaving us with `100px` height instead of `200px`. There are reports that banners are stretched to this height. We need to make sure there aren't any CSS forcing bigger size.

**Comment by iliyaM** [comment]
Banners right now on live site in home page are 200px height. (in css).
they should be 100px?

**Comment by MeanEYE** [comment]
Yes.
