### ISSUE TITLE
Banner uplaod doesnt show

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Bsexy-Shop#171]
When trying to upload Banner to the site, it doesn't show.
![image](https://user-images.githubusercontent.com/26923359/29821181-ab348a5a-8ccf-11e7-83ee-e162e75cf86e.png)

**Comment by MeanEYE** [comment]
@hanan-avzuk stated this is working, but it didn't work when they uploaded. I need to get the same data they tried to upload and it didn't work so I can replicate the issue.
