### ISSUE TITLE
Create 'sex stories' page

### ISSUE THREAD

**Issue by talovdat** [Way2CU/Bsexy-Shop#175]
We need to remove "required" page from the site and replace it with "sex stories"
**Required page:** http://bsexy.co.il/required/required-tel-aviv
![image](https://user-images.githubusercontent.com/26923359/36381913-cde5c4bc-158f-11e8-83d7-035ea421874c.png)

The design for "sex stories" page shared through Google Drive.

![image](https://user-images.githubusercontent.com/26923359/36382569-1411cf92-1592-11e8-807f-95109edc9f7d.png)

A - Title of the story
B - Content about the story
'for more information' button is needed.

**Comment by VladimirWebDev** [comment]
@talovdat I need info, actually design for "more information" button. Where to put it ?
Also, for current /required category link, icon was woman shoe in main navigation. Does it stays the same ?
And need text for that link.

**Comment by talovdat** [comment]
'For more information' Button should match the rest of the site design.
Goes at the bottom of the article window, for example: 
![image](https://user-images.githubusercontent.com/26923359/36544337-e661d22c-17ee-11e8-8296-dfd047911aa8.png)

Text for Icon is סיפורי סקס 
The icon for the category will be provided soon.

**Comment by talovdat** [comment]
Icon stays the same.
![image](https://user-images.githubusercontent.com/26923359/36545287-3e63771c-17f1-11e8-86ec-c31282ca407b.png)

Text for the "more information button" - להמשך הסיפור

**Comment by VladimirWebDev** [comment]
@talovdat 
Preliminary look of category: 
![image](https://user-images.githubusercontent.com/25882157/36638238-d2ed47f0-19ef-11e8-8421-866764476705.png)
After clicking on more information button, whats the page looks like..?
Bunch of text or some images..?

**Comment by talovdat** [comment]
![image](https://user-images.githubusercontent.com/26923359/36639386-30e82cb6-1a14-11e8-92ed-b32ccef8e67e.png)


Such as the above (taken from _http://bsexy.co.il/private/private-tel-aviv/598_)

- Headline for the article/page
- Scrollable Images 
- Content 
*No 'click to call' button.
