### ISSUE TITLE
Banners needs to be associated with sub categories and sub

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Bsexy-Shop#18]
The same categories that appear in items should appear in banners as well.

**Comment by talrez11** [comment]
They are at the moment, but we need to come up with option to show banners that are shown as in subcategories page or on category page have different size

**Comment by MeanEYE** [comment]
This needs updating so categories are on par. 
Also @talrez11 what the hell did that sentence mean?

**Comment by talrez11** [comment]
As far as i know this issue is fixed because we are showing only one template for service items.
