### ISSUE TITLE
Search doesnt work

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Bsexy-Shop#20]
Search doesnt work at all

**Comment by talrez11** [comment]
Site has this error:Notice: Undefined index: search.xml in template "site/templates/parts/header.xml" with query string "private" (/var/www/units/section.php on line 132), referer: http://localhost:8080/
Notice: Array to string conversion in template "site/templates/parts/header.xml" with query string "private" (/var/www/units/url.php on line 49), referer: http://localhost:8080/. This errors repeats itself in couple of projects when using development branch of caracal
