### ISSUE TITLE
Some sort of ALT tag to show name of menu obeject

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Bsexy-Shop#22]
Can we have that?

**Comment by MeanEYE** [comment]
Main menu items do not contain images so they can have `alt` attributes. We can however make `title` attributes for links, but it's redundant as they would contain the same thing as the content of the link itself. To quote [MDN](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title):

> If this attribute is omitted, it means that the title of the nearest ancestor of this element is still relevant for it (and can legitimately be used as the tooltip for that element). If this attribute is set to the empty string, it explicitly means that its nearest ancestor's title is not relevant for this element (and shouldn't be used in the tooltip for that element).

Unless we explicitly want to add some sort of different description or value for this title, there's no need to add it. Am closing this issue. Please reopen if there's need to address this again.
