### ISSUE TITLE
Manage items should show phone number 

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Bsexy-Shop#24]
They are basing their search on that, the ones who update the items.

**Comment by MeanEYE** [comment]
Filtering by manufacturer would solve this? If so this is a duplicate. If there's something else planned for manufacturer please let me know.

**Comment by hanan-avzuk** [comment]
They need to search items by phone numbers

**Comment by MeanEYE** [comment]
The solution will be as I explained. Separate search window in backend which allows searching by phone numbers.
