### ISSUE TITLE
saving with enter does not work

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Bsexy-Shop#30]
When saving image data and pressing enter the system says that information was saved but it wasnt.

**Comment by MeanEYE** [comment]
This needs to be retested after I deploy again. There might have been an issue caused by drag and drop changes which modified a lot of window handling code.

**Comment by MeanEYE** [comment]
@hanan-avzuk can you retest?

**Comment by MeanEYE** [comment]
@iliyaM and @talrez11 please test this one before I start chasing a ghost. Backend didn't see changes that might affect this kind of behavior and am surprised to see it reported. Please make sure to test with two browsers at least to exclude possibility of browser fuckup.

**Comment by MeanEYE** [comment]
Outdated. Reopen if issue exists still and needs fixing.
