### ISSUE TITLE
item date doesnt work

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Bsexy-Shop#35]

**Comment by hanan-avzuk** [comment]
Even tho the date as past item is still shown

**Comment by MeanEYE** [comment]
Just tested this and it works. Care elaborating how this doesn't work?

**Comment by hanan-avzuk** [comment]
[http://bsexy.co.il.82-223-16-124.eu1.way2cu.work/gays/gays-eilat
](url) same item - Item date is 1/1/2015 and it shows
![screenshot from 2016-10-25 10-50-42](https://cloud.githubusercontent.com/assets/18681483/19677698/2652f476-9aa3-11e6-8146-09aa68c67238.png)
![screenshot from 2016-10-25 10-51-10](https://cloud.githubusercontent.com/assets/18681483/19677702/2a910d5c-9aa3-11e6-8786-6cc9a512ce65.png)

**Comment by MeanEYE** [comment]
@talrez11 changed template but didn't include `show_expired=0`. Fixed now.
