### ISSUE TITLE
Fix banners 

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Bsexy-Shop#37]
Banners do not work right, also there should be the exact same categories to choose from as items

**Comment by hanan-avzuk** [comment]
There should be an ability to choose to which categories the banner belogns to through banner management - links management

**Comment by MeanEYE** [comment]
Incomplete information about what doesn't work right. Is this issue meant to be just so we create categories?

**Comment by MeanEYE** [comment]
Duplicate issue!

**Comment by hanan-avzuk** [comment]
It works now :) tho categories should be the exact same as categories for items

**Comment by MeanEYE** [comment]
Will make a copy.
