### ISSUE TITLE
Images doesnt show the title or ALT or whatever

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Bsexy-Shop#42]
http://bsexy.co.il.82-223-16-124.eu1.way2cu.work/promoted/10

**Comment by hanan-avzuk** [comment]
I gave all images there title

**Comment by MeanEYE** [comment]
![screenshot from 2016-10-30 12-05-49](https://cloud.githubusercontent.com/assets/1911594/19836193/38984b14-9e99-11e6-8611-443c63406667.png)
All `alt` attributes visible and populated. This is not an issue. :)
