### ISSUE TITLE
Image upload gets stuck in the end of the process

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Bsexy-Shop#50]
When uploading an image/s to item, you need to get out of the image gallery and then back again in order to see the images. images get uploaded just not shown.

**Comment by MeanEYE** [comment]
@talrez11 can you reproduce this on our server or your own local machine?

**Comment by MeanEYE** [comment]
I need both @talrez11 and @iliyaM to test this and confirm. Because I am still not sure what's going on.

**Comment by iliyaM** [comment]
Confirming

**Comment by MeanEYE** [comment]
Okay, can you elaborate from where did you upload? Just clicked on _Upload_ from all images menu?

**Comment by iliyaM** [comment]
image gallery -> upload multiple images >
the alert box reduces to just title.
after refresh you see that all the images have been uploaded

**Comment by MeanEYE** [comment]
Regular upload works as expected?
