### ISSUE TITLE
new girls at homepage

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Bsexy-Shop#52]
New girls at homepage show only girls from the parent category, that means that the same girls will appear at promoted on homepage and at new to the site.
New to the site girls should show girls from all sub category of that category as well

**Comment by MeanEYE** [comment]
This is going to be difficult to solve if we want to provide flexibility in amount of areas.

**Comment by hanan-avzuk** [comment]
New girls will be the newest girls og the specific category in Tel-Aviv only

**Comment by MeanEYE** [comment]
Actually @talrez11 you can do this one. It's quite simple. When showing new girls, you specify current service + '-tel-aviv' and show that.
