### ISSUE TITLE
Cities menu should have the span thingie as well

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Bsexy-Shop#53]
The cities menu should show the "לעיסוי" svg

**Comment by MeanEYE** [comment]
Am not entirely sure it should. Keeping keyword consistency makes sense when optimizing for SEO, but this is done through SVG exactly to avoid search engines indexing this. But if it's needed, for some reason, someone has to go through and add that span.

**Comment by hanan-avzuk** [comment]
I will go through, just make it count in menu :)

**Comment by hanan-avzuk** [comment]
It is needed cause human eyes should see that its massage and not porn

**Comment by MeanEYE** [comment]
Okay, whatever you want. Please do it on their server then so we don't duplicate work. Once done I'll export db and we'll do the coding part.

**Comment by talrez11** [comment]
I have added style to area menu spans displaying "massage" background image

**Comment by MeanEYE** [comment]
@hanan-avzuk can you confirm this thing is working now properly.
