### ISSUE TITLE
search sucks

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Bsexy-Shop#54]
Doesnt work on desktop and work even worse on mobile

**Comment by MeanEYE** [comment]
You need to be more descriptive in how it doesn't work. What did you search for and expected to see which results. It's going to be hard to find problems and fix them when description is "its no work". Mobile is most likely missing styles.

**Comment by talrez11** [comment]
Fixed issue that search results are not showing on mobile. Seems like i forgot am developing to mobile version as well :)
