### ISSUE TITLE
Title structure 

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Bsexy-Shop#57]
Title structure should be:
{category name}, all the {sub category name} at bsexy site
שם קטגוריה}, כל ה{שם תת קטגוריה} באתר ביסקסי}
דוגמא:
נערות ליווי, כל הנערות ליווי באילת באתר ביסקסי

**Comment by MeanEYE** [comment]
@hanan-avzuk Can you be specific on structure. Because what you just wrote makes shit all sense. We have to have base `site_title` and then add to that remaining parts of the title. But this explanation does nothing other than complicate and confuse any previous understanding if such thing ever existed.

**Comment by hanan-avzuk** [comment]
Eli wants site title to start with {category name}, all the {sub category name} at bsexy site
What is it you dont get? It will look like this only in hebrew:
escort, all the escort in tel aviv at bsexy site 
gays, all the gays in raanana at bsexy site
So basically its what we did only the general site title is at the end and not the beginning and it is "at bsexy site"

**Comment by hanan-avzuk** [comment]
On item page, title structure should be:
{item title} - {category name} - all the {sub category name} at bsexy site
On category page, title should be:
{category name} - all the {sub category name} at bsexy site

**Comment by hanan-avzuk** [comment]
For page : http://185.151.197.11/gays/gays-tel-aviv/42
Title should be: עיסוי מסעיר ואמיתי - גייז - כל הגייז תל אביב באתר ביסקסי
Where: עיסוי מסעיר ואמיתי is the item title
גייז is the category name
כל ה is just string, just words that are between parameters
גייז תל אביב is the sub category name 
ב is just a string
אתר ביסקסי is the site title

**Comment by hanan-avzuk** [comment]
for page: http://185.151.197.11/gays/gays-tel-aviv
Title should be: גייז - כל הגייז תל אביב באתר ביסקסי
Where: גייז is the category name
כל ה is just string, just words that are between parameters
גייז תל אביב is the sub category name
ב is just a string
אתר ביסקסי is the site title
