### ISSUE TITLE
manufacture drop down should be ordered ascending

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Bsexy-Shop#76]
At the manage item there is a manufactures dropdown and itis not ordered and it should be

**Comment by MeanEYE** [comment]
You mean the content of manufacturer menu?

**Comment by hanan-avzuk** [comment]
At the bsexy item management (there is manufacture filter) - There

**Comment by MeanEYE** [comment]
And I repeat the question. You mean content is not sorted?

**Comment by hanan-avzuk** [comment]
![screenshot from 2016-11-28 17-26-47](https://cloud.githubusercontent.com/assets/18681483/20674062/18022efc-b590-11e6-8f51-40e6eb8e1435.png)
I mean this is not sorted

**Comment by MeanEYE** [comment]
It should be now. Can you confirm @hanan-avzuk? Thanks.
