### ISSUE TITLE
Adding GTM to website

### ISSUE THREAD

**Issue by eyalway2cu** [Way2CU/Bsexy-Shop#78]
We need to add GTM code to the website, the code is separated into two when one section goes in the head and the other immediately after opening body tag.

This one goes as high as possible in the head section:

<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-PNSTZ6T');</script>

This one goes immediately after opening body tag:

<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-PNSTZ6T"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>

Let me know if you require anything from me. I didnt publish this yet so if you do implement it and get a 404 error that is because of that.

**Comment by talrez11** [comment]
I have added it on all site pages except sitemap.xml page, ok?

**Comment by eyalway2cu** [comment]
on the live site? I cant see it anywhere.

**Comment by MeanEYE** [comment]
I need to deploy for live site to get it.
