### ISSUE TITLE
Items priority needs to be three levels

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Bsexy-Shop#89]
We set item priority to be 5, 15 and 25 for three defferent levels, It shows only 2. meaning 15 and 25 are the same color...

**Comment by talrez11** [comment]
Fixed home page categories to also display those three levels
0-9: regular,
10-19 - premium,
20-29 - gold.

**Comment by MeanEYE** [comment]
@hanan-avzuk you need to confirm this.
