### ISSUE TITLE
Add 2 Links at the footer

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Bsexy-Shop#94]
Eli wants 2 links at the footer:

1. Should link here: http://www.banana.co.il/Ads.asp?ID=27 - both title and text shown should be: מאגר דירות דיסקרטיות

2. Should link here:http://xfinder.com/he/he/category/%D7%A0%D7%A2%D7%A8%D7%AA-%D7%9C%D7%99%D7%95%D7%95%D7%99 - both title and text shown should be: מאגר נערות ליווי

**Comment by talrez11** [comment]
Do i need any kind of design for that, or to just create them out of my head?

**Comment by talrez11** [comment]
Site need to be deployed in order to see the links
