### ISSUE TITLE
Banner should also show banner title 

### ISSUE THREAD

**Issue by hanan-avzuk** [Way2CU/Bsexy-Shop#96]
Add `title` attribute to the banner link.

**Comment by MeanEYE** [comment]
Also, fix class name. `add` means to add something, `ad` is short for advertisement.

**Comment by talrez11** [comment]
This is strange but when changing class name that contains the word ad, browser blocks those banners.

**Comment by MeanEYE** [comment]
Ah, okay. That's AdBlock at work. We should find a different name then.

**Comment by talrez11** [comment]
Banners class are "link"
